/**
 * 功能分类配置
 * 将所有工具按照创作流程进行分类，符合创作者使用习惯
 */

export interface ToolCategory {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  gradient: string;
  tools: Tool[];
}

export interface Tool {
  id: string;
  name: string;
  description: string;
  href: string;
  icon?: string;
  isNew?: boolean;
  isPro?: boolean;
  isHot?: boolean;
}

export const toolCategories: ToolCategory[] = [
  {
    id: 'character',
    name: '角色设定',
    description: '人物创作全流程工具',
    icon: '👤',
    color: 'blue',
    gradient: 'from-blue-500 to-indigo-600',
    tools: [
      {
        id: 'characters',
        name: '角色生成器',
        description: '一键创建立体角色，包含外貌、性格、背景等',
        href: '/characters',
        icon: '✨',
        isHot: true,
      },
      {
        id: 'relationship-map',
        name: '人物关系图',
        description: '可视化角色关系，理清复杂人物网络',
        href: '/relationship-map',
        icon: '🔗',
      },
      {
        id: 'character-backstory',
        name: '角色背景故事',
        description: '生成角色成长经历和背景设定',
        href: '/character-backstory',
        icon: '📜',
      },
      {
        id: 'character-dialogue',
        name: '角色对话风格',
        description: '设计独特的角色说话方式',
        href: '/character-dialogue',
        icon: '💬',
      },
      {
        id: 'character-arc',
        name: '角色成长弧',
        description: '规划角色从开始到结尾的成长轨迹',
        href: '/character-arc',
        icon: '📈',
      },
      {
        id: 'character-secrets',
        name: '角色秘密设定',
        description: '为角色设计隐藏的秘密和伏笔',
        href: '/character-secrets',
        icon: '🔐',
      },
      {
        id: 'character-power',
        name: '角色能力体系',
        description: '设计角色的技能、魔法或超能力',
        href: '/character-power',
        icon: '⚡',
        isNew: true,
      },
      {
        id: 'character-name',
        name: '角色命名生成',
        description: '生成符合作品风格的角色名字',
        href: '/character-name',
        icon: '🏷️',
      },
      {
        id: 'character-appearance',
        name: '外貌特征生成',
        description: '详细描述角色外貌和着装',
        href: '/character-appearance',
        icon: '👔',
      },
      {
        id: 'character-psychology',
        name: '心理分析报告',
        description: '深度分析角色心理和动机',
        href: '/character-psychology',
        icon: '🧠',
      },
      {
        id: 'character-voice',
        name: '角色声音特征',
        description: '描述角色的声音特点',
        href: '/character-voice',
        icon: '🎤',
      },
      {
        id: 'character-motivation',
        name: '角色动机分析',
        description: '分析角色行为背后的深层动机',
        href: '/character-motivation',
        icon: '🎯',
      },
      {
        id: 'character-conflict',
        name: '角色冲突设计',
        description: '设计角色之间的矛盾和冲突',
        href: '/character-conflict',
        icon: '⚔️',
      },
      {
        id: 'character-group',
        name: '角色群体设计',
        description: '设计团队、家族、组织等角色群体',
        href: '/character-group',
        icon: '👥',
      },
      {
        id: 'character-evolution',
        name: '角色演变规划',
        description: '规划角色在故事中的变化过程',
        href: '/character-evolution',
        icon: '🦋',
      },
    ],
  },
  {
    id: 'plot',
    name: '情节设计',
    description: '剧情创作工具集',
    icon: '📖',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-600',
    tools: [
      {
        id: 'outline-generator',
        name: '大纲生成',
        description: '生成完整小说大纲，分章规划',
        href: '/outline-generator',
        icon: '📋',
        isHot: true,
      },
      {
        id: 'plot-twist',
        name: '情节反转',
        description: '生成意想不到的剧情反转点',
        href: '/plot-twist',
        icon: '🔄',
      },
      {
        id: 'world-building',
        name: '世界观设定',
        description: '构建完整的小说世界观',
        href: '/world-building',
        icon: '🌍',
      },
      {
        id: 'ending-generator',
        name: '结局生成',
        description: '设计满意的小说结局',
        href: '/ending-generator',
        icon: '🏁',
      },
      {
        id: 'scene-design',
        name: '场景设计',
        description: '设计具体的剧情场景和冲突',
        href: '/scene-design',
        icon: '🎬',
        isNew: true,
      },
      {
        id: 'chapter-structure',
        name: '章节结构规划',
        description: '设计章节的开头、发展、高潮、结尾',
        href: '/chapter-structure',
        icon: '📚',
      },
      {
        id: 'subplot-design',
        name: '副线故事设计',
        description: '设计陪衬主线的故事支线',
        href: '/subplot-design',
        icon: '🌳',
      },
      {
        id: 'climax-builder',
        name: '高潮场景构建',
        description: '构建故事的高潮部分',
        href: '/climax-builder',
        icon: '🎆',
      },
      {
        id: 'pacing-control',
        name: '节奏控制',
        description: '调整故事的快慢节奏',
        href: '/pacing-control',
        icon: '⏱️',
      },
      {
        id: 'foreshadowing',
        name: '伏笔设计',
        description: '设计后续剧情的伏笔',
        href: '/foreshadowing',
        icon: '🔮',
      },
      {
        id: 'tension-builder',
        name: '悬念构建',
        description: '制造紧张和悬念氛围',
        href: '/tension-builder',
        icon: '😰',
      },
      {
        id: 'revelation-scene',
        name: '揭秘场景',
        description: '设计真相揭晓的关键场景',
        href: '/revelation-scene',
        icon: '💡',
      },
      {
        id: 'conflict-escalation',
        name: '冲突升级',
        description: '逐步升级故事中的冲突',
        href: '/conflict-escalation',
        icon: '📈',
      },
      {
        id: 'multi-perspective',
        name: '多视角叙事',
        description: '设计多角色视角的叙事结构',
        href: '/multi-perspective',
        icon: '👁️',
      },
      {
        id: 'timeline-design',
        name: '时间线设计',
        description: '设计故事的时间线和插叙',
        href: '/timeline-design',
        icon: '⏰',
      },
    ],
  },
  {
    id: 'writing',
    name: '智能写作',
    description: 'AI辅助创作工具',
    icon: '✍️',
    color: 'cyan',
    gradient: 'from-cyan-500 to-teal-600',
    tools: [
      {
        id: 'continue',
        name: '智能续写',
        description: '根据上下文智能续写内容',
        href: '/continue',
        icon: '🚀',
        isHot: true,
      },
      {
        id: 'workspace',
        name: '精修润色',
        description: '润色优化文章质量',
        href: '/workspace',
        icon: '⭐',
        isNew: true,
      },
      {
        id: 'style-simulator',
        name: '文风模拟',
        description: '模拟不同作者风格',
        href: '/style-simulator',
        icon: '🎨',
      },
      {
        id: 'chapter-writer',
        name: '章节撰写',
        description: '生成完整章节内容',
        href: '/chapter-writer',
        icon: '📝',
        isHot: true,
      },
      {
        id: 'dialogue-generator',
        name: '对话生成',
        description: '生成自然的角色对话',
        href: '/dialogue-generator',
        icon: '💬',
      },
      {
        id: 'description-enhancer',
        name: '描写增强',
        description: '增强环境、动作、心理描写',
        href: '/description-enhancer',
        icon: '🖼️',
      },
      {
        id: 'opening-hook',
        name: '黄金开头',
        description: '生成引人入胜的开头段落',
        href: '/opening-hook',
        icon: '🪝',
        isHot: true,
      },
      {
        id: 'transition-smoother',
        name: '过渡句优化',
        description: '优化段落间的过渡衔接',
        href: '/transition-smoother',
        icon: '🔗',
      },
      {
        id: 'metaphor-generator',
        name: '比喻修辞',
        description: '生成生动的比喻和修辞',
        href: '/metaphor-generator',
        icon: '🎭',
      },
      {
        id: 'emotional-writer',
        name: '情感描写',
        description: '增强情感表达的深度',
        href: '/emotional-writer',
        icon: '❤️',
      },
      {
        id: 'action-scene',
        name: '动作场景',
        description: '描写激烈的动作场面',
        href: '/action-scene',
        icon: '🏃',
      },
      {
        id: 'romance-scene',
        name: '情感场景',
        description: '描写细腻的情感互动',
        href: '/romance-scene',
        icon: '💕',
      },
      {
        id: 'battle-scene',
        name: '战斗场景',
        description: '描写精彩的战斗场面',
        href: '/battle-scene',
        icon: '⚔️',
      },
      {
        id: 'inner-monologue',
        name: '内心独白',
        description: '描写角色的内心活动',
        href: '/inner-monologue',
        icon: '🧘',
      },
      {
        id: 'flashback-scene',
        name: '回忆场景',
        description: '描写回忆和插叙内容',
        href: '/flashback-scene',
        icon: '⏪',
      },
    ],
  },
  {
    id: 'optimization',
    name: '润色优化',
    description: '内容质量提升工具',
    icon: '💎',
    color: 'amber',
    gradient: 'from-amber-500 to-orange-600',
    tools: [
      {
        id: 'satisfaction-engine',
        name: '爽点引擎',
        description: '识别并增强爽点密度',
        href: '/satisfaction-engine',
        icon: '🎯',
        isHot: true,
      },
      {
        id: 'writer-block',
        name: '卡文诊断',
        description: '诊断创作卡顿问题',
        href: '/writer-block',
        icon: '💡',
      },
      {
        id: 'explosive-analyze',
        name: '爆款拆解',
        description: '分析爆款小说成功要素',
        href: '/explosive-analyze',
        icon: '📊',
        isNew: true,
      },
      {
        id: 'grammar-check',
        name: '语法检查',
        description: '检查并修正语法错误',
        href: '/grammar-check',
        icon: '✅',
      },
      {
        id: 'redundancy-remover',
        name: '冗余去除',
        description: '去除重复和冗余表达',
        href: '/redundancy-remover',
        icon: '🗑️',
      },
      {
        id: 'logic-check',
        name: '逻辑检查',
        description: '检查剧情逻辑合理性',
        href: '/logic-check',
        icon: '🔍',
      },
      {
        id: 'pacing-analyzer',
        name: '节奏分析',
        description: '分析故事节奏分布',
        href: '/pacing-analyzer',
        icon: '📈',
      },
      {
        id: 'readability-score',
        name: '可读性评分',
        description: '评估文本的可读性水平',
        href: '/readability-score',
        icon: '📊',
      },
      {
        id: 'character-consistency',
        name: '角色一致性',
        description: '检查角色性格的一致性',
        href: '/character-consistency',
        icon: '👤',
      },
      {
        id: 'dialogue-polisher',
        name: '对话润色',
        description: '优化对话的自然度',
        href: '/dialogue-polisher',
        icon: '💬',
      },
      {
        id: 'emotion-deepener',
        name: '情感深化',
        description: '增强情感表达的感染力',
        href: '/emotion-deepener',
        icon: '💖',
      },
      {
        id: 'suspense-builder',
        name: '悬念增强',
        description: '增强故事的悬念感',
        href: '/suspense-builder',
        icon: '😱',
      },
      {
        id: 'climax-enhancer',
        name: '高潮强化',
        description: '增强高潮场景的冲击力',
        href: 'climax-enhancer',
        icon: '🎆',
      },
      {
        id: 'ending-polisher',
        name: '结尾润色',
        description: '优化结尾的感染力',
        href: '/ending-polisher',
        icon: '🏁',
      },
      {
        id: 'title-optimizer',
        name: '标题优化',
        description: '优化章节标题的吸引力',
        href: '/title-optimizer',
        icon: '🏷️',
      },
    ],
  },
  {
    id: 'creative',
    name: '创意工具',
    description: '激发创作灵感',
    icon: '🎪',
    color: 'rose',
    gradient: 'from-rose-500 to-red-600',
    tools: [
      {
        id: 'title-generator',
        name: '书名生成',
        description: '生成吸引眼球的小说标题',
        href: '/title-generator',
        icon: '📚',
      },
      {
        id: 'cover-generator',
        name: '封面描述',
        description: '生成封面描述，助力封面设计',
        href: '/cover-generator',
        icon: '🖼️',
      },
      {
        id: 'genre-blender',
        name: '题材融合',
        description: '创新融合多种题材元素',
        href: '/genre-blender',
        icon: '🌈',
        isNew: true,
      },
      {
        id: 'concept-generator',
        name: '概念生成',
        description: '生成独特的故事概念',
        href: '/concept-generator',
        icon: '💡',
      },
      {
        id: 'setting-idea',
        name: '场景创意',
        description: '生成新颖的场景设定',
        href: '/setting-idea',
        icon: '🏰',
      },
      {
        id: 'trope-twister',
        name: '套路反转',
        description: '创新性地反转经典套路',
        href: '/trope-twister',
        icon: '🔄',
      },
      {
        id: 'what-if-scenario',
        name: '假设场景',
        description: '生成"如果...会怎样"的创意',
        href: '/what-if-scenario',
        icon: '❓',
      },
      {
        id: 'character-archetype',
        name: '原型创新',
        description: '创新角色原型',
        href: '/character-archetype',
        icon: '🎭',
      },
      {
        id: 'theme-explorer',
        name: '主题探索',
        description: '深化故事主题',
        href: '/theme-explorer',
        icon: '🎯',
      },
      {
        id: 'symbolism-creator',
        name: '象征设计',
        description: '设计故事中的象征元素',
        href: '/symbolism-creator',
        icon: '🔮',
      },
      {
        id: 'motif-designer',
        name: '母题设计',
        description: '设计反复出现的母题',
        href: '/motif-designer',
        icon: '🔄',
      },
      {
        id: 'hook-ideas',
        name: '钩子创意',
        description: '生成吸引读者的钩子',
        href: '/hook-ideas',
        icon: '🪝',
      },
      {
        id: 'twist-ideas',
        name: '反转创意',
        description: '生成剧情反转灵感',
        href: '/twist-ideas',
        icon: '🌀',
      },
      {
        id: 'climax-ideas',
        name: '高潮创意',
        description: '生成高潮场景灵感',
        href: '/climax-ideas',
        icon: '🎆',
      },
      {
        id: 'crossover-concept',
        name: '跨界概念',
        description: '生成跨界融合的概念',
        href: '/crossover-concept',
        icon: '🌐',
      },
    ],
  },
  {
    id: 'materials',
    name: '素材资源',
    description: '素材库与参考资源',
    icon: '📦',
    color: 'emerald',
    gradient: 'from-emerald-500 to-green-600',
    tools: [
      {
        id: 'materials',
        name: '百万素材库',
        description: '古代常识、民俗神话、写作技巧',
        href: '/materials',
        icon: '💾',
        isHot: true,
      },
      {
        id: 'myth-database',
        name: '神话数据库',
        description: '中外神话传说资料库',
        href: '/myth-database',
        icon: '🐉',
      },
      {
        id: 'history-facts',
        name: '历史常识',
        description: '历史背景和年代常识',
        href: '/history-facts',
        icon: '📜',
      },
      {
        id: 'martial-arts',
        name: '武术资料库',
        description: '武术流派、招式、兵器',
        href: '/martial-arts',
        icon: '🥋',
      },
      {
        id: 'magic-system',
        name: '魔法体系',
        description: '魔法、修真、仙侠体系',
        href: '/magic-system',
        icon: '✨',
      },
      {
        id: 'geography-data',
        name: '地理资料',
        description: '山川河流、气候地理',
        href: '/geography-data',
        icon: '🏔️',
      },
      {
        id: 'custom-culture',
        name: '民俗文化',
        description: '民俗、礼仪、节日',
        href: '/custom-culture',
        icon: '🎎',
      },
      {
        id: 'weapon-encyclopedia',
        name: '兵器百科',
        description: '古今中外兵器资料',
        href: '/weapon-encyclopedia',
        icon: '⚔️',
      },
      {
        id: 'medicine-ancient',
        name: '古代医学',
        description: '中医、草药、养生',
        href: '/medicine-ancient',
        icon: '🌿',
      },
      {
        id: 'architecture-ancient',
        name: '古代建筑',
        description: '宫殿、民居、城池',
        href: '/architecture-ancient',
        icon: '🏛️',
      },
      {
        id: 'clothing-ancient',
        name: '服饰资料',
        description: '历代服饰、发饰、妆容',
        href: '/clothing-ancient',
        icon: '👗',
      },
      {
        id: 'food-culture',
        name: '饮食文化',
        description: '古代饮食、酒文化',
        href: '/food-culture',
        icon: '🍜',
      },
      {
        id: 'music-ancient',
        name: '古代音乐',
        description: '乐器、乐律、戏曲',
        href: '/music-ancient',
        icon: '🎵',
      },
      {
        id: 'poetry-database',
        name: '诗词库',
        description: '古诗词、楹联、成语',
        href: '/poetry-database',
        icon: '📖',
      },
      {
        id: 'idiom-dictionary',
        name: '成语词典',
        description: '成语典故、出处解释',
        href: '/idiom-dictionary',
        icon: '📕',
      },
    ],
  },
  {
    id: 'genre',
    name: '题材专精',
    description: '针对特定题材的专业工具',
    icon: '🎬',
    color: 'indigo',
    gradient: 'from-indigo-500 to-violet-600',
    tools: [
      {
        id: 'urban-fantasy',
        name: '都市玄幻',
        description: '都市题材专用写作工具',
        href: '/urban-fantasy',
        icon: '🏙️',
        isHot: true,
      },
      {
        id: 'cultivation',
        name: '仙侠修真',
        description: '仙侠修真题材专用工具',
        href: '/cultivation',
        icon: '🧘',
      },
      {
        id: 'historical',
        name: '历史小说',
        description: '历史题材专用工具',
        href: '/historical',
        icon: '📜',
      },
      {
        id: 'romance',
        name: '言情情感',
        description: '言情题材专用工具',
        href: '/romance',
        icon: '💕',
      },
      {
        id: 'mystery',
        name: '悬疑推理',
        description: '悬疑推理专用工具',
        href: '/mystery',
        icon: '🔍',
      },
      {
        id: 'scifi',
        name: '科幻未来',
        description: '科幻题材专用工具',
        href: '/scifi',
        icon: '🚀',
      },
      {
        id: 'fantasy',
        name: '奇幻魔法',
        description: '奇幻题材专用工具',
        href: '/fantasy',
        icon: '🧙',
      },
      {
        id: 'horror',
        name: '恐怖惊悚',
        description: '恐怖题材专用工具',
        href: '/horror',
        icon: '👻',
      },
      {
        id: 'military',
        name: '军事战争',
        description: '军事题材专用工具',
        href: '/military',
        icon: '🎖️',
      },
      {
        id: 'sports',
        name: '体育竞技',
        description: '体育题材专用工具',
        href: '/sports',
        icon: '🏆',
      },
      {
        id: 'campus',
        name: '校园青春',
        description: '校园题材专用工具',
        href: '/campus',
        icon: '🏫',
      },
      {
        id: 'business',
        name: '商业商战',
        description: '商战题材专用工具',
        href: '/business',
        icon: '💼',
      },
      {
        id: 'thriller',
        name: '谍战特工',
        description: '谍战题材专用工具',
        href: '/thriller',
        icon: '🕵️',
      },
      {
        id: 'zombie',
        name: '末世求生',
        description: '末世题材专用工具',
        href: '/zombie',
        icon: '🧟',
      },
      {
        id: 'time-travel',
        name: '穿越重生',
        description: '穿越题材专用工具',
        href: '/time-travel',
        icon: '⏰',
      },
    ],
  },
  {
    id: 'analysis',
    name: '数据分析',
    description: '创作数据分析和优化',
    icon: '📊',
    color: 'teal',
    gradient: 'from-teal-500 to-cyan-600',
    tools: [
      {
        id: 'read-analytics',
        name: '阅读数据分析',
        description: '分析读者阅读行为数据',
        href: '/read-analytics',
        icon: '📈',
        isNew: true,
      },
      {
        id: 'word-count',
        name: '字数分析',
        description: '分析字数分布和进度',
        href: '/word-count',
        icon: '📊',
      },
      {
        id: 'chapter-performance',
        name: '章节表现',
        description: '分析各章节读者反馈',
        href: '/chapter-performance',
        icon: '📚',
      },
      {
        id: 'reader-feedback',
        name: '读者反馈分析',
        description: '分析评论和反馈数据',
        href: '/reader-feedback',
        icon: '💬',
      },
      {
        id: 'completion-rate',
        name: '完读率分析',
        description: '分析完读率变化趋势',
        href: '/completion-rate',
        icon: '✅',
      },
      {
        id: 'retention-curve',
        name: '留存曲线',
        description: '分析读者留存情况',
        href: '/retention-curve',
        icon: '📉',
      },
      {
        id: 'hotspot-analysis',
        name: '热点分析',
        description: '识别故事中的热门内容',
        href: '/hotspot-analysis',
        icon: '🔥',
      },
      {
        id: 'genre-trends',
        name: '题材趋势',
        description: '分析热门题材趋势',
        href: '/genre-trends',
        icon: '📊',
      },
      {
        id: 'competitor-analysis',
        name: '竞品分析',
        description: '分析同类作品表现',
        href: '/competitor-analysis',
        icon: '🎯',
      },
      {
        id: 'writing-pattern',
        name: '写作模式',
        description: '分析个人写作模式',
        href: '/writing-pattern',
        icon: '📝',
      },
      {
        id: 'quality-score',
        name: '质量评分',
        description: '综合评估作品质量',
        href: '/quality-score',
        icon: '⭐',
      },
      {
        id: 'growth-tracker',
        name: '成长追踪',
        description: '追踪写作成长轨迹',
        href: '/growth-tracker',
        icon: '📈',
      },
      {
        id: 'recommendation-engine',
        name: '推荐引擎',
        description: 'AI推荐优化建议',
        href: '/recommendation-engine',
        icon: '🤖',
        isNew: true,
      },
      {
        id: 'a-b-test',
        name: 'A/B测试',
        description: '测试不同版本效果',
        href: '/a-b-test',
        icon: '🧪',
      },
      {
        id: 'report-generator',
        name: '报告生成',
        description: '生成数据分析报告',
        href: '/report-generator',
        icon: '📋',
      },
    ],
  },
  {
    id: 'collaboration',
    name: '协作功能',
    description: '团队协作和版本控制',
    icon: '🤝',
    color: 'violet',
    gradient: 'from-violet-500 to-purple-600',
    tools: [
      {
        id: 'real-time-edit',
        name: '实时协作',
        description: '多人实时编辑同一作品',
        href: '/real-time-edit',
        icon: '✏️',
        isNew: true,
      },
      {
        id: 'version-control',
        name: '版本控制',
        description: '追踪和管理历史版本',
        href: '/version-control',
        icon: '🔄',
      },
      {
        id: 'comment-system',
        name: '评论标注',
        description: '对文本进行评论和标注',
        href: '/comment-system',
        icon: '💬',
      },
      {
        id: 'share-work',
        name: '作品分享',
        description: '分享作品给协作者',
        href: '/share-work',
        icon: '🔗',
      },
      {
        id: 'team-workspace',
        name: '团队空间',
        description: '创建和管理团队项目',
        href: '/team-workspace',
        icon: '👥',
      },
      {
        id: 'permission-manage',
        name: '权限管理',
        description: '管理协作者权限',
        href: '/permission-manage',
        icon: '🔐',
      },
      {
        id: 'activity-log',
        name: '活动日志',
        description: '查看协作活动记录',
        href: '/activity-log',
        icon: '📝',
      },
      {
        id: 'merge-changes',
        name: '变更合并',
        description: '合并不同作者的修改',
        href: '/merge-changes',
        icon: '🔀',
      },
      {
        id: 'conflict-resolve',
        name: '冲突解决',
        description: '解决编辑冲突',
        href: '/conflict-resolve',
        icon: '⚔️',
      },
      {
        id: 'notification',
        name: '协作通知',
        description: '接收协作动态通知',
        href: '/notification',
        icon: '🔔',
      },
      {
        id: 'task-assign',
        name: '任务分配',
        description: '分配写作任务',
        href: '/task-assign',
        icon: '✅',
      },
      {
        id: 'review-process',
        name: '审阅流程',
        description: '设置内容审阅流程',
        href: '/review-process',
        icon: '👁️',
      },
      {
        id: 'export-collaboration',
        name: '协作导出',
        description: '导出协作成果',
        href: '/export-collaboration',
        icon: '📤',
      },
      {
        id: 'backup-sync',
        name: '备份同步',
        description: '自动备份和同步',
        href: '/backup-sync',
        icon: '💾',
      },
      {
        id: 'integration',
        name: '第三方集成',
        description: '集成其他协作工具',
        href: '/integration',
        icon: '🔌',
      },
    ],
  },
  {
    id: 'protection',
    name: '版权保护',
    description: '版权保护和内容安全',
    icon: '🛡️',
    color: 'slate',
    gradient: 'from-slate-500 to-gray-600',
    tools: [
      {
        id: 'digital-watermark',
        name: '数字水印',
        description: '为作品添加数字水印',
        href: '/digital-watermark',
        icon: '💧',
        isNew: true,
      },
      {
        id: 'timestamp-proof',
        name: '时间戳证明',
        description: '生成创作时间戳证明',
        href: '/timestamp-proof',
        icon: '⏰',
      },
      {
        id: 'originality-check',
        name: '原创检测',
        description: '检测内容原创性',
        href: '/originality-check',
        icon: '🔍',
      },
      {
        id: 'plagiarism-check',
        name: '抄袭检测',
        description: '检测抄袭内容',
        href: '/plagiarism-check',
        icon: '⚠️',
      },
      {
        id: 'copyright-register',
        name: '版权登记',
        description: '协助版权登记流程',
        href: '/copyright-register',
        icon: '📜',
      },
      {
        id: 'content-encryption',
        name: '内容加密',
        description: '加密保护敏感内容',
        href: '/content-encryption',
        icon: '🔐',
      },
      {
        id: 'access-control',
        name: '访问控制',
        description: '控制内容访问权限',
        href: '/access-control',
        icon: '🚫',
      },
      {
        id: 'leak-detection',
        name: '泄露监测',
        description: '监测内容泄露情况',
        href: '/leak-detection',
        icon: '👁️',
      },
      {
        id: 'dmca-report',
        name: '侵权报告',
        description: '生成侵权投诉报告',
        href: '/dmca-report',
        icon: '📄',
      },
      {
        id: 'license-manage',
        name: '授权管理',
        description: '管理内容授权',
        href: '/license-manage',
        icon: '📋',
      },
      {
        id: 'audit-trail',
        name: '审计追踪',
        description: '追踪内容变更记录',
        href: '/audit-trail',
        icon: '📊',
      },
      {
        id: 'compliance-check',
        name: '合规检查',
        description: '检查平台合规要求',
        href: '/compliance-check',
        icon: '✅',
      },
      {
        id: 'sensitive-filter',
        name: '敏感词过滤',
        description: '过滤敏感内容',
        href: '/sensitive-filter',
        icon: '🚫',
      },
      {
        id: 'auto-backup',
        name: '自动备份',
        description: '自动备份保护内容',
        href: '/auto-backup',
        icon: '💾',
      },
      {
        id: 'recovery-tool',
        name: '恢复工具',
        description: '恢复误删或损坏内容',
        href: '/recovery-tool',
        icon: '♻️',
      },
    ],
  },
  {
    id: 'platform',
    name: '平台对接',
    description: '多平台发布和对接',
    icon: '🌐',
    color: 'fuchsia',
    gradient: 'from-fuchsia-500 to-pink-600',
    tools: [
      {
        id: 'fanqie-publish',
        name: '番茄小说发布',
        description: '直接发布到番茄小说',
        href: '/fanqie-publish',
        icon: '🍅',
        isHot: true,
      },
      {
        id: 'qidian-sync',
        name: '起点同步',
        description: '同步内容到起点',
        href: '/qidian-sync',
        icon: '📚',
      },
      {
        id: 'jjwxc-upload',
        name: '晋江上传',
        description: '上传到晋江文学城',
        href: '/jjwxc-upload',
        icon: '🌸',
      },
      {
        id: 'zongheng-post',
        name: '纵横发布',
        description: '发布到纵横中文网',
        href: '/zongheng-post',
        icon: '⚔️',
      },
      {
        id: 'feilu-sync',
        name: '飞卢同步',
        description: '同步到飞卢小说网',
        href: '/feilu-sync',
        icon: '🚀',
      },
      {
        id: '17k-upload',
        name: '17K上传',
        description: '上传到17K小说网',
        href: '/17k-upload',
        icon: '📖',
      },
      {
        id: 'multi-platform',
        name: '多平台管理',
        description: '统一管理多个平台账号',
        href: '/multi-platform',
        icon: '🔗',
      },
      {
        id: 'format-convert',
        name: '格式转换',
        description: '转换不同平台格式',
        href: '/format-convert',
        icon: '🔄',
      },
      {
        id: 'publish-schedule',
        name: '发布计划',
        description: '规划和定时发布',
        href: '/publish-schedule',
        icon: '📅',
      },
      {
        id: 'analytics-sync',
        name: '数据同步',
        description: '同步平台阅读数据',
        href: '/analytics-sync',
        icon: '📊',
      },
      {
        id: 'comment-sync',
        name: '评论同步',
        description: '同步读者评论',
        href: '/comment-sync',
        icon: '💬',
      },
      {
        id: 'revenue-track',
        name: '收益追踪',
        description: '追踪各平台收益',
        href: '/revenue-track',
        icon: '💰',
      },
      {
        id: 'api-connector',
        name: 'API连接器',
        description: '连接平台API接口',
        href: '/api-connector',
        icon: '🔌',
      },
      {
        id: 'auto-publish',
        name: '自动发布',
        description: '设置自动发布规则',
        href: '/auto-publish',
        icon: '🤖',
      },
      {
        id: 'cross-platform-stat',
        name: '跨平台统计',
        description: '统计跨平台表现',
        href: '/cross-platform-stat',
        icon: '📈',
      },
    ],
  },
  {
    id: 'community',
    name: '社区功能',
    description: '社区互动和社交功能',
    icon: '👥',
    color: 'orange',
    gradient: 'from-orange-500 to-amber-600',
    tools: [
      {
        id: 'community-forum',
        name: '社区论坛',
        description: '创作者交流论坛',
        href: '/community-forum',
        icon: '💬',
        isNew: true,
      },
      {
        id: 'author-circle',
        name: '作者圈子',
        description: '创建作者交流圈',
        href: '/author-circle',
        icon: '⭕',
      },
      {
        id: 'work-share',
        name: '作品分享',
        description: '分享作品到社区',
        href: '/work-share',
        icon: '📤',
      },
      {
        id: 'comment-system',
        name: '评论互动',
        description: '评论和点赞功能',
        href: '/comment-system',
        icon: '👍',
      },
      {
        id: 'follow-author',
        name: '关注作者',
        description: '关注喜欢的作者',
        href: '/follow-author',
        icon: '👁️',
      },
      {
        id: 'recommendation',
        name: '推荐推荐',
        description: '推荐优质作品',
        href: '/recommendation',
        icon: '⭐',
      },
      {
        id: 'discussion',
        name: '话题讨论',
        description: '参与话题讨论',
        href: '/discussion',
        icon: '💭',
      },
      {
        id: 'ranking',
        name: '排行榜',
        description: '社区作品排行',
        href: '/ranking',
        icon: '🏆',
      },
      {
        id: 'live-chat',
        name: '实时聊天',
        description: '作者实时交流',
        href: '/live-chat',
        icon: '💬',
      },
      {
        id: 'event',
        name: '活动赛事',
        description: '参与创作活动',
        href: '/event',
        icon: '🎉',
      },
      {
        id: 'mentorship',
        name: '师徒制度',
        description: '导师带新作者',
        href: '/mentorship',
        icon: '🎓',
      },
      {
        id: 'critique',
        name: '作品点评',
        description: '互相点评作品',
        href: '/critique',
        icon: '📝',
      },
      {
        id: 'resource-share',
        name: '资源分享',
        description: '分享创作资源',
        href: '/resource-share',
        icon: '📦',
      },
      {
        id: 'showcase',
        name: '作品展示',
        description: '展示优秀作品',
        href: '/showcase',
        icon: '🖼️',
      },
      {
        id: 'social-share',
        name: '社交分享',
        description: '分享到社交平台',
        href: '/social-share',
        icon: '🔗',
      },
    ],
  },
  {
    id: 'ai-tuning',
    name: 'AI微调',
    description: '个性化AI模型优化',
    icon: '🤖',
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-600',
    tools: [
      {
        id: 'prompt-optimizer',
        name: '提示词优化',
        description: '优化AI生成提示词',
        href: '/prompt-optimizer',
        icon: '📝',
        isNew: true,
      },
      {
        id: 'style-training',
        name: '风格训练',
        description: '训练特定写作风格',
        href: '/style-training',
        icon: '🎨',
      },
      {
        id: 'feedback-learning',
        name: '反馈学习',
        description: '基于用户反馈优化',
        href: '/feedback-learning',
        icon: '📊',
      },
      {
        id: 'custom-model',
        name: '自定义模型',
        description: '创建个性化AI模型',
        href: '/custom-model',
        icon: '🧠',
      },
      {
        id: 'temperature-tune',
        name: '创造性调节',
        description: '调节AI创造性程度',
        href: '/temperature-tune',
        icon: '🌡️',
      },
      {
        id: 'quality-control',
        name: '质量控制',
        description: '控制生成内容质量',
        href: '/quality-control',
        icon: '✅',
      },
      {
        id: 'preference-memory',
        name: '偏好记忆',
        description: '记忆用户写作偏好',
        href: '/preference-memory',
        icon: '🧠',
      },
      {
        id: 'context-aware',
        name: '上下文感知',
        description: '增强上下文理解',
        href: '/context-aware',
        icon: '🔍',
      },
      {
        id: 'output-length',
        name: '输出长度',
        description: '控制生成内容长度',
        href: '/output-length',
        icon: '📏',
      },
      {
        id: 'tone-adjust',
        name: '语气调节',
        description: '调节AI输出语气',
        href: '/tone-adjust',
        icon: '🗣️',
      },
      {
        id: 'consistency-check',
        name: '一致性检查',
        description: '检查内容一致性',
        href: '/consistency-check',
        icon: '🔄',
      },
      {
        id: 'auto-complete',
        name: '自动补全',
        description: '智能自动补全',
        href: '/auto-complete',
        icon: '⚡',
      },
      {
        id: 'multi-style',
        name: '多风格切换',
        description: '快速切换不同风格',
        href: '/multi-style',
        icon: '🎭',
      },
      {
        id: 'batch-generate',
        name: '批量生成',
        description: '批量生成内容',
        href: '/batch-generate',
        icon: '📦',
      },
      {
        id: 'ai-assistant',
        name: 'AI助手',
        description: '个性化AI写作助手',
        href: '/ai-assistant',
        icon: '🤖',
      },
    ],
  },
  {
    id: 'management',
    name: '作品管理',
    description: '创作项目管理',
    icon: '📁',
    color: 'slate',
    gradient: 'from-slate-500 to-gray-600',
    tools: [
      {
        id: 'works',
        name: '我的作品',
        description: '管理所有创作作品',
        href: '/works',
        icon: '📝',
      },
      {
        id: 'stats',
        name: '数据统计',
        description: '查看创作数据统计',
        href: '/stats',
        icon: '📈',
      },
      {
        id: 'profile',
        name: '个人中心',
        description: '账号设置与管理',
        href: '/profile',
        icon: '⚙️',
      },
    ],
  },
];

// 快捷工具（高频使用）
export const quickTools: Tool[] = [
  {
    id: 'continue',
    name: '智能续写',
    description: '快速续写内容',
    href: '/continue',
    icon: '🚀',
    isHot: true,
  },
  {
    id: 'workspace',
    name: '精修润色',
    description: '润色优化',
    href: '/workspace',
    icon: '⭐',
    isNew: true,
  },
  {
    id: 'characters',
    name: '角色生成',
    description: '创建角色',
    href: '/characters',
    icon: '👤',
  },
  {
    id: 'outline-generator',
    name: '大纲生成',
    description: '生成大纲',
    href: '/outline-generator',
    icon: '📋',
    isHot: true,
  },
  {
    id: 'materials',
    name: '素材库',
    description: '查找素材',
    href: '/materials',
    icon: '💾',
  },
];

// 新功能展示
export const newFeatures: Tool[] = [
  {
    id: 'workspace',
    name: '精修润色',
    description: '专业润色工具，提升作品质量',
    href: '/workspace',
    icon: '⭐',
    isNew: true,
  },
  {
    id: 'explosive-analyze',
    name: '爆款拆解',
    description: '深度分析爆款成功要素',
    href: '/explosive-analyze',
    icon: '📊',
    isNew: true,
  },
  {
    id: 'editor-review',
    name: '模拟审稿',
    description: '双视角专业审稿',
    href: '/editor-review',
    icon: '👁️',
    isNew: true,
  },
];

// 获取分类颜色映射
export const getCategoryColor = (categoryId: string): string => {
  const category = toolCategories.find(cat => cat.id === categoryId);
  return category?.color || 'gray';
};

// 获取分类渐变映射
export const getCategoryGradient = (categoryId: string): string => {
  const category = toolCategories.find(cat => cat.id === categoryId);
  return category?.gradient || 'from-gray-500 to-gray-600';
};
